// Real Chrome + real HTTP + isolated PostgreSQL. No API doubles or application fixtures.
const fs=require('fs'),path=require('path'),os=require('os'),cp=require('child_process'),assert=require('assert/strict'),{randomUUID}=require('crypto');
const delay=ms=>new Promise(r=>setTimeout(r,ms));const origin=process.env.SETTINGS_BROWSER_ORIGIN||'http://127.0.0.1:5175',api=process.env.ACCEPTANCE_API;
if(api!=='http://127.0.0.1:4001'||!process.env.ACCEPTANCE_DATABASE?.startsWith('spendsense_goals_test_acceptance_')||new URL(process.env.DATABASE_URL).pathname.slice(1)!==process.env.ACCEPTANCE_DATABASE)throw Error('Isolated acceptance environment required');
async function request(route,method='GET',body,token){const r=await fetch(api+route,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});if(!r.ok)throw Error('Acceptance HTTP '+method+' '+route+' '+r.status);return r.json();}
async function setup(){
 const {prisma}=require('../dist/lib/prisma');
 const account=async label=>{const email=randomUUID()+'@example.invalid',password=randomUUID();await request('/auth/register','POST',{email,password});const login=await request('/auth/login','POST',{email,password});const token=login.token,s=await request('/settings','GET',undefined,token);await request('/settings','PUT',{displayName:label,income:null,paydayDay:null,primaryGoalId:null,budgetMonth:s.budgetMonth,budgetAmount:null,notifyNearLimit:false,notifyExceeded:false,notifyAnomaly:false},token);return {token};};
 const a=await account('Acceptance A'),b=await account('Acceptance B');const category=await prisma.category.create({data:{name:'Acceptance-A-'+randomUUID().slice(0,8),type:'expense'}}),other=await prisma.category.create({data:{name:'Acceptance-B-'+randomUUID().slice(0,8),type:'expense'}});
 const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),today=['year','month','day'].map(k=>parts.find(p=>p.type===k).value).join('-');
 for(let i=0;i<30;i++){const d=new Date(today+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-60+i);await request('/transactions','POST',{categoryId:category.id,type:'expense',amount:'100.00',transactionDate:d.toISOString().slice(0,10),transactionTime:null},a.token);}
 const bs=await request('/settings','GET',undefined,b.token);await request('/settings','PUT',{displayName:'Acceptance B',income:null,paydayDay:null,primaryGoalId:null,budgetMonth:bs.budgetMonth,budgetAmount:null,notifyNearLimit:false,notifyExceeded:false,notifyAnomaly:true},b.token);
 const small=await request('/transactions','POST',{categoryId:other.id,type:'expense',amount:'1.00',transactionDate:today,transactionTime:null},b.token);
 assert.equal((await request('/transactions/'+small.id+'/anomaly','GET',undefined,b.token)).latestEvaluation.outcome,'not_evaluated');assert.equal((await request('/notifications','GET',undefined,b.token)).items.length,0);console.log('PASS real HTTP insufficient history produces no notification');
 return {a,b,category,other,small,prisma};
}
const initialize=token=>{localStorage.setItem('spendsense_token',token);window.alert=()=>{};window.confirm=()=>true;const native=window.fetch.bind(window);window.__createdId=null;window.fetch=async(url,options={})=>{const r=await native(url,options);if(String(url).endsWith('/transactions')&&options.method==='POST'&&r.ok){const body=await r.clone().json();window.__createdId=body.id;}return r;};};(async()=>{
 const fixture=await setup();
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'spendsense-settings-browser-'));const browser=cp.spawn(process.env.SETTINGS_CHROME_PATH||'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--user-data-dir='+dir,'about:blank'],{windowsHide:true,stdio:'ignore'});
 let socket;try{for(let i=0;i<100&&!fs.existsSync(path.join(dir,'DevToolsActivePort'));i++)await delay(100);const port=fs.readFileSync(path.join(dir,'DevToolsActivePort'),'utf8').split('\n')[0];const targets=await(await fetch('http://127.0.0.1:'+port+'/json/list')).json();socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j;});let protocolId=0;const pending=new Map();socket.onmessage=e=>{const msg=JSON.parse(e.data);if(msg.id){const pair=pending.get(msg.id);pending.delete(msg.id);if(msg.error)pair.reject(Error(msg.error.message));else pair.resolve(msg.result);}};const send=(method,params={})=>new Promise((resolve,reject)=>{const key=++protocolId;pending.set(key,{resolve,reject});socket.send(JSON.stringify({id:key,method,params}));});
 const evaluate=async(expression)=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,userGesture:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};const waitFor=async(expr)=>{for(let i=0;i<100;i++){if(await evaluate(expr))return;await delay(50);}throw Error('Timed out: '+expr);};
 await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Page.addScriptToEvaluateOnNewDocument',{source:'('+initialize.toString()+')('+JSON.stringify(fixture.a.token)+')'});
 const navigate=async route=>{await send('Page.navigate',{url:origin+route});};
 await navigate('/settings');await waitFor("Boolean(document.querySelector('#settings-name'))");
 const toggle="[...document.querySelectorAll('input[role=switch]')][2]";
 assert.equal(await evaluate(toggle+'.checked'),false);
 for(const enabled of [true,false,true]){await evaluate(toggle+'.click()');await evaluate("document.querySelector('button[type=submit]').click()");await waitFor("document.querySelector('.settings-success')?.textContent.includes('บันทึก')");await navigate('/settings');await waitFor("Boolean(document.querySelector('#settings-name'))");assert.equal(await evaluate(toggle+'.checked'),enabled);}
 console.log('PASS real Settings enable/disable persisted across refresh');
 await navigate('/transactions/add');await waitFor("document.querySelector('select')?.options.length>1");
 await evaluate("document.querySelector('select').value="+JSON.stringify(fixture.category.id)+";document.querySelector('select').dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('input[type=number]').focus()");await send('Input.insertText',{text:'250.00'});
 assert.equal(await evaluate("document.querySelector('input[type=time]').value"),'');await evaluate("[...document.querySelectorAll('button')].find(b=>b.textContent.includes('บันทึก')&&!b.textContent.includes('ยกเลิก')).click()");await waitFor('Boolean(window.__createdId)');const id=await evaluate('window.__createdId');
 const first=await request('/transactions/'+id+'/anomaly','GET',undefined,fixture.a.token);assert.equal(first.latestEvaluation.outcome,'flagged');const originalSnapshot=JSON.stringify(first.notificationSnapshot);let notices=await request('/notifications','GET',undefined,fixture.a.token);assert.equal(notices.items.length,1);const notice=notices.items[0];
 await evaluate("document.querySelector('.user-header-notification').click()");await waitFor("Boolean(document.querySelector('.notification-item'))");await evaluate("document.querySelector('.notification-item').click()");await waitFor("document.querySelectorAll('.anomaly-review h5').length===2&&[...document.querySelectorAll('.anomaly-review h5')].every(e=>e.textContent.includes('ยังไม่ได้ตรวจสอบ'))");
 assert.equal((await request('/anomaly/evaluations/'+first.latestEvaluation.id+'/reviews','GET',undefined,fixture.a.token)).reviewState,'unreviewed');assert.ok((await request('/notifications','GET',undefined,fixture.a.token)).items[0].readAt);console.log('PASS real create produces one notice; reading leaves review unreviewed');
 await evaluate("document.querySelector('.anomaly-details summary').focus()");await send('Input.dispatchKeyEvent',{type:'keyDown',key:' ',code:'Space',windowsVirtualKeyCode:32});await send('Input.dispatchKeyEvent',{type:'keyUp',key:' ',code:'Space',windowsVirtualKeyCode:32});await waitFor("document.querySelector('.anomaly-details').open");
 for(const [index,state,eligible] of [[0,'confirmed_normal',true],[1,'confirmed_problem',false],[0,'confirmed_normal',true],[1,'confirmed_problem',false]]){
  await evaluate("[...document.querySelectorAll('.anomaly-review')].at(-1).querySelectorAll('button')["+index+"].focus()");await send('Input.dispatchKeyEvent',{type:'keyDown',key:' ',code:'Space',windowsVirtualKeyCode:32});await send('Input.dispatchKeyEvent',{type:'keyUp',key:' ',code:'Space',windowsVirtualKeyCode:32});
  const text=state==='confirmed_normal'?'ยืนยันว่าปกติ':'ยืนยันว่ามีปัญหา';await waitFor("[...document.querySelectorAll('.anomaly-review h5')].length===2&&[...document.querySelectorAll('.anomaly-review h5')].every(e=>e.textContent.includes("+JSON.stringify(text)+"))");
  const detail=await request('/transactions/'+id+'/anomaly','GET',undefined,fixture.a.token);assert.equal(detail.amountBaselineEligible,eligible);assert.equal(detail.timeBaselineEligible,false);assert.equal(JSON.stringify(detail.notificationSnapshot),originalSnapshot);
 }
 const history=await request('/anomaly/evaluations/'+first.latestEvaluation.id+'/reviews','GET',undefined,fixture.a.token);assert.deepEqual(history.reviewHistory.items.map(r=>r.sequence),[4,3,2,1]);console.log('PASS real keyboard review/changes of mind; amount eligible only when allowed, time remains excluded; immutable snapshot');
 await send('Network.setBlockedURLs',{urls:['*transactions/'+id+'/anomaly*']});await navigate('/transactions/'+id+'/edit');await waitFor("Boolean(document.querySelector('.anomaly-details [role=alert] button'))");await send('Network.setBlockedURLs',{urls:[]});await evaluate("document.querySelector('.anomaly-details').open=true;document.querySelector('.anomaly-details [role=alert] button').click()");await waitFor("document.querySelectorAll('.anomaly-review h5').length===2");console.log('PASS real network failure and retry without API mocks');
 const editAmount=async amount=>{await waitFor("Boolean(document.querySelector('.edit-field input[type=number]'))");await evaluate("(()=>{const el=document.querySelector('.edit-field input[type=number]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,"+JSON.stringify(amount)+");el.dispatchEvent(new Event('input',{bubbles:true}));})()");await evaluate("document.querySelector('.edit-save-button').click()");await waitFor("location.pathname==='/transactions'");};
 await editAmount('100.00');const second=await request('/transactions/'+id+'/anomaly','GET',undefined,fixture.a.token);assert.equal(second.currentRevision,2);assert.equal(second.latestEvaluation.outcome,'not_flagged');assert.equal(second.reviewState,'unreviewed');assert.equal(second.amountBaselineEligible,true);assert.equal(JSON.stringify(second.notificationSnapshot),originalSnapshot);
 await navigate('/transactions/'+id+'/edit');await editAmount('400.00');const third=await request('/transactions/'+id+'/anomaly','GET',undefined,fixture.a.token);assert.equal(third.currentRevision,3);assert.equal(third.latestEvaluation.outcome,'flagged');assert.equal(third.reviewState,'unreviewed');assert.equal(third.amountBaselineEligible,false);assert.equal((await request('/notifications','GET',undefined,fixture.a.token)).items.length,1);console.log('PASS real edit creates independent revisions; nonflagged automatically eligible; reflagged unreviewed and no duplicate notice');
 await waitFor("Boolean(document.querySelector('.history-menu-button'))");await evaluate("document.querySelector('.history-menu-button').click()");await waitFor("Boolean(document.querySelector('.history-menu-dropdown .delete'))");await evaluate("document.querySelector('.history-menu-dropdown .delete').click()");await waitFor("!document.querySelector('.history-menu-dropdown')");
 const deleted=await request('/notifications/'+notice.id+'/anomaly','GET',undefined,fixture.a.token);assert.equal(deleted.sourceState,'deleted');assert.equal(JSON.stringify(deleted.notificationSnapshot),originalSnapshot);
 await evaluate("document.querySelector('.user-header-notification').click()");await waitFor("Boolean(document.querySelector('.notification-item'))");await evaluate("document.querySelector('.notification-item').click()");await waitFor("document.querySelector('.anomaly-details')?.textContent.includes('รายการต้นทางถูกลบแล้ว')");await evaluate("document.querySelector('.anomaly-details').open=true");assert.equal(await evaluate("Boolean(document.querySelector('.anomaly-details a'))"),false);console.log('PASS real delete retains readable notice, snapshots and review history');
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});assert.equal(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'),true);assert.equal(await evaluate("document.querySelector('.notification-dialog').scrollWidth<=document.querySelector('.notification-dialog').clientWidth+1"),true);console.log('PASS real mobile dialog and keyboard controls');
 // Hold an actual response at CDP, without replacing its payload, across a session switch.
 let held=[],releaseHeld;const paused=new Promise(r=>releaseHeld=r);const previousHandler=socket.onmessage;
 socket.onmessage=event=>{const message=JSON.parse(event.data);if(message.method==='Fetch.requestPaused'){held.push(message.params.requestId);releaseHeld();}else previousHandler(event);};
 await send('Fetch.enable',{patterns:[{urlPattern:api+'/notifications/'+notice.id+'/anomaly',requestStage:'Response'}]});
 await navigate('/transactions');await waitFor("Boolean(document.querySelector('.user-header-notification'))");await evaluate("document.querySelector('.user-header-notification').click()");await waitFor("Boolean(document.querySelector('.notification-item'))");await evaluate("document.querySelector('.notification-item').click()");await Promise.race([paused,new Promise((_,reject)=>setTimeout(()=>reject(Error('Expected actual response pause')),10000))]);
 await evaluate("localStorage.setItem('spendsense_token',"+JSON.stringify(fixture.b.token)+");window.dispatchEvent(new Event('spendsense-session'));history.pushState({},'',"+JSON.stringify('/transactions/'+fixture.small.id+'/edit')+");window.dispatchEvent(new PopStateEvent('popstate'))");await waitFor("document.querySelector('.user-header-info strong')?.textContent==='Acceptance B'&&document.querySelector('.edit-field input[type=number]')?.value==='1'");
 for(const requestId of held)await send('Fetch.continueRequest',{requestId}).catch(()=>{});await send('Fetch.disable');await evaluate("new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))");assert.equal(await evaluate("document.body.textContent.includes('Acceptance A')"),false);assert.equal(await evaluate("document.querySelector('.edit-field input[type=number]').value"),'1');console.log('PASS real held response cannot overwrite another session');
 await send('Browser.close').catch(()=>{});
 }finally{socket?.close();browser.kill();await fixture.prisma.$disconnect();console.log('Real browser acceptance used isolated synthetic accounts; no application fixtures.');}
})().catch(e=>{console.error(e.message);process.exitCode=1;});