// Real Chrome, API doubles only; no application database calls.
const fs=require('fs'),path=require('path'),os=require('os'),cp=require('child_process'),assert=require('assert/strict');
const delay=ms=>new Promise(r=>setTimeout(r,ms));const origin=process.env.SETTINGS_BROWSER_ORIGIN||'http://127.0.0.1:5173';
const mock=()=>{
 const native=window.fetch.bind(window);window.__calls=[];
 window.fetch=async(url,options={})=>{
  if(!String(url).startsWith('http://localhost:4000'))return native(url,options);
  const route=new URL(url).pathname,session=new Headers(options.headers).get('Authorization')?.replace('Bearer ','');window.__calls.push({route,body:options.body});let value={};
  if(route==='/profile')value={userId:session,email:session+'@example.invalid',displayName:session,hasAvatar:false};
  else if(route==='/categories')value=[{id:'cat',name:'ทดสอบ',type:'expense'}];
  else if(route==='/settings'){if(options.method==='PUT')window.__saved=JSON.parse(options.body);value={userId:session,email:'test@example.invalid',displayName:session,income:null,paydayDay:null,primaryGoalId:null,goals:[],budgetMonth:'2026-09',budgetAmount:null,notifications:{notifyNearLimit:false,notifyExceeded:false,notifyAnomaly:window.__saved?.notifyAnomaly??false}};}
  else if(route==='/notifications')value={items:[{id:window.__noticeId||'notice',type:'transaction_anomaly',title:'รายการที่ควรตรวจสอบ',message:'ข้อมูลจำลองสำหรับ UI',readAt:null,createdAt:'2026-09-23T00:00:00Z'}],unreadCount:1};
  else if(route==='/notifications/anomaly/reconcile')value={processed:10,evaluated:10,hasMore:true,nextCursor:'next-id',asOfDate:'2026-09-23'};
  else if(route.endsWith('/anomaly')){
   if(window.__slow&&session==='session-a')await new Promise(r=>setTimeout(r,700));
   if(window.__fail){return new Response('{}',{status:503});}
   const evaluation=revision=>({revision,ruleVersion:'synthetic-ui',evaluatedAt:'2026-09-23T00:00:00Z',outcome:'flagged',snapshot:{transaction:{amount:revision===1?'250.00':'300.00',categoryName:session+' ชื่อหมวดยาว'.repeat(20),date:'2026-09-01',time:null,timeConfirmed:false},window:{startDate:'2026-03-05',endExclusive:'2026-09-01'},baseline:{n:30,days:30,span:29,median:'100',mad:'0',q1:'100',q3:'100',timeN:0,timeDays:0,timeSpan:0,bucketCount:0,nearbyCount:0},rules:{amountMin:30,amountDays:10,amountSpan:28,timeMin:60,timeDays:20,timeSpan:42,timeCoverage:'0.8',zThreshold:'3.5',iqrMultiplier:'3',minimumDifference:'100',medianDifferenceRatio:'0.5',rareFrequency:'0.05'},assessment:{amount:{status:'flagged',reasonCode:'amount_zero_dispersion'},time:{status:'not_evaluated',reasonCode:'time_not_confirmed'}}}});
   value={sourceState:'deleted',pending:false,notificationSnapshot:evaluation(1),latestEvaluation:evaluation(2),latestAppliesToCurrent:false,transactionLink:null};
  }
  return new Response(JSON.stringify(value),{headers:{'Content-Type':'application/json'}});
 };localStorage.setItem('spendsense_token','session-a');
};
(async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'spendsense-settings-browser-'));const browser=cp.spawn(process.env.SETTINGS_CHROME_PATH||'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--user-data-dir='+dir,'about:blank'],{windowsHide:true,stdio:'ignore'});
 let socket;try{for(let i=0;i<100&&!fs.existsSync(path.join(dir,'DevToolsActivePort'));i++)await delay(100);const port=fs.readFileSync(path.join(dir,'DevToolsActivePort'),'utf8').split('\n')[0];const targets=await(await fetch('http://127.0.0.1:'+port+'/json/list')).json();socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j;});let id=0;const pending=new Map();socket.onmessage=e=>{const msg=JSON.parse(e.data);if(msg.id){const pair=pending.get(msg.id);pending.delete(msg.id);if(msg.error)pair.reject(Error(msg.error.message));else pair.resolve(msg.result);}};const send=(method,params={})=>new Promise((resolve,reject)=>{const key=++id;pending.set(key,{resolve,reject});socket.send(JSON.stringify({id:key,method,params}));});
 const evaluate=async(expression)=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,userGesture:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};const waitFor=async(expr)=>{for(let i=0;i<100;i++){if(await evaluate(expr))return;await delay(50);}throw Error('Timed out: '+expr);};
 await send('Page.enable');await send('Runtime.enable');await send('Page.addScriptToEvaluateOnNewDocument',{source:'('+mock.toString()+')()'});await send('Page.navigate',{url:origin+'/transactions/add'});await waitFor("Boolean(document.querySelector('input[type=time]'))");
 assert.equal(await evaluate("document.querySelector('input[type=time]').value"),'');assert.equal(await evaluate("document.querySelector('input[type=checkbox]').checked"),false);assert.equal(await evaluate("document.querySelector('input[type=checkbox]').disabled"),true);console.log('PASS time starts empty and cannot be automatically confirmed');
 await send('Page.navigate',{url:origin+'/settings'});await waitFor("document.querySelectorAll('input[role=switch]').length===4");
 await evaluate("window.__toggle=[...document.querySelectorAll('input[role=switch]')][2];window.__toggle.focus()");assert.equal(await evaluate('window.__toggle.disabled'),false);assert.equal(await evaluate('window.__toggle.checked'),false);
 await send('Input.dispatchKeyEvent',{type:'keyDown',key:' ',code:'Space',windowsVirtualKeyCode:32});await send('Input.dispatchKeyEvent',{type:'keyUp',key:' ',code:'Space',windowsVirtualKeyCode:32});await evaluate("document.querySelector('button[type=submit]').click()");await waitFor('window.__saved?.notifyAnomaly===true');console.log('PASS Settings keyboard toggle and explicit save');
 await evaluate("document.querySelector('.user-header-notification').click()");await waitFor("Boolean(document.querySelector('.notification-item'))");await evaluate("window.__fail=true;document.querySelector('.notification-item').click()");await waitFor("Boolean(document.querySelector('.anomaly-details [role=alert] button'))");await evaluate("window.__fail=false;document.querySelector('.anomaly-details [role=alert] button').click()");await waitFor("document.querySelector('.anomaly-details')?.textContent.includes('revision 2')");console.log('PASS detail error and retry');
 await evaluate("document.querySelector('.anomaly-details summary').focus()");await send('Input.dispatchKeyEvent',{type:'keyDown',key:' ',code:'Space',windowsVirtualKeyCode:32});await send('Input.dispatchKeyEvent',{type:'keyUp',key:' ',code:'Space',windowsVirtualKeyCode:32});await waitFor("document.querySelector('.anomaly-details').open");assert.ok(await evaluate("document.querySelector('.anomaly-details').textContent.includes('revision 1')"));assert.ok(await evaluate("document.querySelector('.anomaly-details').textContent.includes('รายการต้นทางถูกลบแล้ว')"));assert.equal(await evaluate("document.querySelector('.anomaly-details a')"),null);console.log('PASS immutable notification snapshot and latest evaluation separately; deleted source has no link');
 await evaluate("[...document.querySelectorAll('button')].find(b=>b.textContent==='ตรวจรายการที่ค้าง').click()");await waitFor("document.body.textContent.includes('ตรวจรายการชุดถัดไป')");await evaluate("[...document.querySelectorAll('button')].find(b=>b.textContent==='ตรวจรายการชุดถัดไป').click()");await waitFor("window.__calls.some(c=>c.route==='/notifications/anomaly/reconcile'&&JSON.parse(c.body).cursor==='next-id')");console.log('PASS bounded reconcile cursor; budget endpoint retained');
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});assert.equal(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'),true);assert.equal(await evaluate("document.querySelector('.notification-dialog').scrollWidth<=document.querySelector('.notification-dialog').clientWidth+1"),true);console.log('PASS mobile long snapshot does not overflow');
 await evaluate("window.__slow=true;window.__noticeId='other';[...document.querySelectorAll('button')].find(b=>b.textContent==='ตรวจงบและโหลดใหม่').click()");await waitFor("!document.querySelector('.notification-dialog > p[role=status]')");await evaluate("document.querySelector('.notification-item').click()");await waitFor("Boolean(document.querySelector('.anomaly-details [role=status]'))");
 await evaluate("localStorage.setItem('spendsense_token','session-b');window.dispatchEvent(new Event('spendsense-session'))");await waitFor("document.querySelector('.user-header-info strong')?.textContent==='session-b'");await evaluate("document.querySelector('.user-header-notification').click()");await waitFor("Boolean(document.querySelector('.notification-item'))");await evaluate("document.querySelector('.notification-item').click()");await waitFor("document.querySelector('.anomaly-details')?.textContent.includes('session-b')");await delay(850);assert.equal(await evaluate("document.querySelector('.anomaly-details').textContent.includes('session-a')"),false);console.log('PASS session switch clears previous account snapshot');
 await send('Browser.close').catch(()=>{});
 }finally{socket?.close();browser.kill();console.log('API mocks only; temporary Chrome profile retained outside repository.');}
})().catch(e=>{console.error(e.message);process.exitCode=1;});