import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import jwt from 'jsonwebtoken';import {Client} from 'pg';
import {prisma} from '../src/lib/prisma';import {app} from '../src/index';import {checkTransactionAnomaly,anomalyBaseline,withAnomalyLock} from '../src/lib/anomaly';import {screenExpense,RULE_VERSION} from '../src/lib/anomalyRules';
const db=new URL(process.env.DATABASE_URL!).pathname.slice(1);if(!db.startsWith('spendsense_goals_test_')||process.env.GOALS_TEST_DATABASE!==db)throw Error('Isolated anomaly database required');
test('anomaly PostgreSQL / HTTP / append-only / committed concurrency',async t=>{
 process.env.JWT_SECRET=randomUUID();const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const addr=server.address();assert.ok(addr&&typeof addr!=='string');t.after(async()=>{await new Promise<void>(r=>server.close(()=>r()));await prisma.$disconnect();});
 const account=async()=>{const u=await prisma.user.create({data:{email:randomUUID()+'@example.invalid',passwordHash:'synthetic-no-login'}});return {...u,userId:u.id,token:jwt.sign({userId:u.id,email:u.email,authVersion:u.authVersion},process.env.JWT_SECRET!)};};const a=await account(),b=await account();
 const cat=await prisma.category.create({data:{name:randomUUID(),type:'expense'}}),other=await prisma.category.create({data:{name:randomUUID(),type:'expense'}}),inc=await prisma.category.create({data:{name:randomUUID(),type:'income'}});
 const data=(amount='250',categoryId=cat.id)=>({type:'expense',categoryId,amount,transactionDate:'2026-09-01',transactionTime:null});
 async function req(path:string,method='GET',body?:unknown,status=200,who=a){const r=await fetch('http://127.0.0.1:'+addr.port+path,{method,headers:{Authorization:'Bearer '+who.token,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const value=await r.json() as any;assert.equal(r.status,status,path+' '+JSON.stringify(value));return value;}
 async function toggle(enabled:boolean,who=a){const s=await req('/settings','GET',undefined,200,who);return req('/settings','PUT',{displayName:'synthetic',income:null,paydayDay:null,primaryGoalId:null,budgetMonth:s.budgetMonth,budgetAmount:null,notifyNearLimit:false,notifyExceeded:false,notifyAnomaly:enabled},200,who);}
 const pending=()=>prisma.transaction.create({data:{userId:a.id,type:'expense',categoryId:cat.id,amount:'250',transactionDate:new Date('2026-09-01T00:00:00Z'),anomalyRevision:1,anomalyPending:true}});
 let noticeId:string,target:any;
 await t.test('defaults false, legacy time unconfirmed, enable does not backfill, auth',async()=>{assert.equal((await req('/settings')).notifications.notifyAnomaly,false);const old=await req('/transactions','POST',{...data('100'),transactionTime:'12:00'},201);assert.equal(old.transactionTimeConfirmed,false);assert.equal(old.anomalyPending,false);await toggle(true);assert.equal(await prisma.anomalyEvaluation.count({where:{userId:a.id}}),0);assert.equal((await req('/notifications/anomaly/reconcile','POST',{})).processed,0);assert.equal((await fetch('http://127.0.0.1:'+addr.port+'/notifications/anomaly/reconcile',{method:'POST'})).status,401);await req('/notifications/anomaly/reconcile','POST',{userId:b.id},400);await req('/notifications/anomaly/reconcile','POST',{limit:51},400);await req('/transactions','POST',{...data(),transactionTimeConfirmed:true},400);});
 await prisma.transaction.createMany({data:Array.from({length:30},(_,i)=>({id:randomUUID(),userId:a.id,categoryId:cat.id,type:'expense' as const,amount:'100',transactionDate:new Date(Date.UTC(2026,7,i+1))}))});
 await t.test('actual numeric SQL median/MAD/quartiles, same-day and account/category isolation',async()=>{await prisma.transaction.create({data:{userId:b.id,categoryId:cat.id,type:'expense',amount:'99999',transactionDate:new Date('2026-08-01')}});const row=await pending();const result=await prisma.$transaction(tx=>anomalyBaseline(tx,row));assert.equal(result.baseline.n,30);assert.equal(result.baseline.median,'100');assert.equal(result.baseline.mad,'0');assert.equal(result.baseline.q1,'100');assert.equal(result.baseline.q3,'100');assert.equal(screenExpense('250',false,result.baseline).amount.reasonCode,'amount_zero_dispersion');await prisma.transaction.delete({where:{id:row.id}});});
 await t.test('create, snapshot vs latest, one notification across revisions, no accidental confirmation',async()=>{target=await req('/transactions','POST',data(),201);const first=await req('/transactions/'+target.id+'/anomaly');assert.equal(first.latestEvaluation.outcome,'flagged');assert.equal(first.notificationSnapshot.revision,1);const notice=await prisma.notification.findUniqueOrThrow({where:{userId_eventKey:{userId:a.id,eventKey:'transaction-anomaly:'+target.id}}});noticeId=notice.id;const original=notice.message;await req('/transactions/'+target.id,'PUT',{...data('300'),transactionTime:'02:00',transactionTimeConfirmed:true});const second=await req('/notifications/'+noticeId+'/anomaly');assert.equal(second.notificationSnapshot.revision,1);assert.equal(second.latestEvaluation.revision,2);assert.equal(second.sourceState,'modified');assert.equal(await prisma.notification.count({where:{userId:a.id,eventKey:notice.eventKey}}),1);assert.equal((await prisma.notification.findUniqueOrThrow({where:{id:noticeId}})).message,original);const before=await prisma.anomalyEvaluation.count({where:{userId:a.id,originalTransactionId:target.id}});await req('/transactions/'+target.id,'PUT',{...data('300'),transactionTime:'02:00',note:'only note'});assert.equal(await prisma.anomalyEvaluation.count({where:{userId:a.id,originalTransactionId:target.id}}),before+1);await req('/transactions/'+target.id,'PUT',{...data('300'),transactionTime:'03:00'});assert.equal((await prisma.transaction.findUniqueOrThrow({where:{id:target.id}})).transactionTimeConfirmed,false);await req('/notifications/'+noticeId+'/anomaly','GET',undefined,404,b);});
 await t.test('append-only and evaluation source ownership are enforced in PostgreSQL',async()=>{const evaluation=await prisma.anomalyEvaluation.findFirstOrThrow({where:{userId:a.id}});await assert.rejects(prisma.anomalyEvaluation.update({where:{id:evaluation.id},data:{outcome:'not_flagged'}}));await assert.rejects(prisma.anomalyEvaluation.delete({where:{id:evaluation.id}}));await assert.rejects(prisma.anomalyEvaluation.create({data:{userId:b.id,originalTransactionId:target.id,revision:3,ruleVersion:RULE_VERSION,outcome:'flagged',snapshot:{}}}));});
 await t.test('delete before evaluation cancels; delete after evaluation preserves immutable snapshot',async()=>{const row=await pending();await req('/transactions/'+row.id,'DELETE');assert.equal(await checkTransactionAnomaly(a,row.id),true);assert.equal(await prisma.anomalyEvaluation.count({where:{originalTransactionId:row.id}}),0);const old=await req('/notifications/'+noticeId+'/anomaly');await req('/transactions/'+target.id,'DELETE');const after=await req('/notifications/'+noticeId+'/anomaly');assert.equal(after.sourceState,'deleted');assert.equal(after.transactionLink,null);assert.deepEqual(after.notificationSnapshot,old.notificationSnapshot);});
 await t.test('failure after committed CRUD leaves pending for retry',async()=>{const c=new Client({connectionString:process.env.DATABASE_URL});await c.connect();try{await c.query(`CREATE FUNCTION test_anomaly_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic failure'; END $$; CREATE TRIGGER test_anomaly_failure BEFORE INSERT ON "AnomalyEvaluation" FOR EACH ROW EXECUTE FUNCTION test_anomaly_failure()`);const item=await req('/transactions','POST',data(),201);assert.equal((await prisma.transaction.findUniqueOrThrow({where:{id:item.id}})).anomalyPending,true);assert.equal(await prisma.anomalyEvaluation.count({where:{originalTransactionId:item.id}}),0);await c.query('DROP TRIGGER test_anomaly_failure ON "AnomalyEvaluation"; DROP FUNCTION test_anomaly_failure()');assert.equal(await checkTransactionAnomaly(a,item.id),true);assert.equal((await prisma.transaction.findUniqueOrThrow({where:{id:item.id}})).anomalyPending,false);}finally{await c.end();}});
 await t.test('concurrent committed reconcile is duplicate-safe; bounded cursor and disable cancels',async()=>{const rows=await Promise.all([pending(),pending(),pending()]);const first=await req('/notifications/anomaly/reconcile','POST',{limit:1});assert.equal(first.processed,1);assert.equal(first.hasMore,true);assert.ok(first.nextCursor);await Promise.all([req('/notifications/anomaly/reconcile','POST',{limit:1,cursor:first.nextCursor}),req('/notifications/anomaly/reconcile','POST',{limit:50})]);for(const row of rows){assert.equal(await prisma.notification.count({where:{userId:a.id,eventKey:'transaction-anomaly:'+row.id}}),1);assert.equal(await prisma.anomalyEvaluation.count({where:{userId:a.id,originalTransactionId:row.id}}),1);}const disabled=await pending();await toggle(false);assert.equal((await prisma.transaction.findUniqueOrThrow({where:{id:disabled.id}})).anomalyPending,false);await toggle(true);await req('/notifications/anomaly/reconcile','POST',{});assert.equal(await prisma.anomalyEvaluation.count({where:{originalTransactionId:disabled.id}}),0);});
 await t.test('latest revision only; expense to income cancels and settings legacy body preserves toggle',async()=>{const row=await pending();await prisma.transaction.update({where:{id:row.id},data:{amount:'400',anomalyRevision:2}});await checkTransactionAnomaly(a,row.id);assert.equal((await prisma.anomalyEvaluation.findFirstOrThrow({where:{originalTransactionId:row.id}})).revision,2);const next=await pending();await req('/transactions/'+next.id,'PUT',{...data('250',inc.id),type:'income'});assert.equal(await prisma.anomalyEvaluation.count({where:{originalTransactionId:next.id}}),0);const s=await req('/settings');await req('/settings','PUT',{displayName:'legacy',income:null,paydayDay:null,primaryGoalId:null,budgetMonth:s.budgetMonth,budgetAmount:null,notifyNearLimit:false,notifyExceeded:false});assert.equal((await req('/settings')).notifications.notifyAnomaly,true);});
 await t.test('time buckets cross midnight, use confirmed wall-clock only, do not use createdAt',async()=>{await prisma.transaction.createMany({data:Array.from({length:60},(_,i)=>({id:randomUUID(),userId:a.id,categoryId:other.id,type:'expense' as const,amount:'100',transactionDate:new Date(Date.UTC(2026,5,i+1)),transactionTime:new Date('1970-01-01T23:55:00Z'),transactionTimeConfirmed:true}))});const row=await prisma.transaction.create({data:{userId:a.id,categoryId:other.id,type:'expense',amount:'100',transactionDate:new Date('2026-09-01'),transactionTime:new Date('1970-01-01T00:05:00Z'),transactionTimeConfirmed:true}});const d=await prisma.$transaction(tx=>anomalyBaseline(tx,row));assert.equal(d.baseline.timeN,60);assert.equal(d.baseline.bucketCount,0);assert.equal(d.baseline.nearbyCount,60);assert.equal(screenExpense('100',true,d.baseline).time.status,'not_flagged');const rare=await req('/transactions','POST',{...data('100',other.id),transactionTime:'08:00',transactionTimeConfirmed:true},201);assert.equal((await req('/transactions/'+rare.id+'/anomaly')).latestEvaluation.snapshot.assessment.time.status,'flagged');});
 await t.test('180-day cutoff, leap day, exact Decimal and bounded aggregate SQL',async()=>{
  const owner=await account(),category=await prisma.category.create({data:{name:randomUUID(),type:'expense'}});
  const end=new Date('2024-03-01'),start=new Date(end);start.setUTCDate(start.getUTCDate()-180);const outside=new Date(start);outside.setUTCDate(outside.getUTCDate()-1);
  await prisma.transaction.createMany({data:[{date:start,amount:'0.07'},{date:new Date('2024-02-29'),amount:'0.09'},{date:outside,amount:'999'},{date:end,amount:'999'}].map(x=>({userId:owner.id,categoryId:category.id,type:'expense' as const,amount:x.amount,transactionDate:x.date}))});
  const row=await prisma.transaction.create({data:{userId:owner.id,categoryId:category.id,type:'expense',amount:'0.08',transactionDate:end}});
  let sql='',returned=0;
  const result=await prisma.$transaction(async tx=>anomalyBaseline(new Proxy(tx,{get(target,key){if(key==='$queryRaw')return async(query:any)=>{sql=query.strings.join('?');const rows=await target.$queryRaw<any[]>(query);returned=rows.length;return rows;};return Reflect.get(target,key);}}),row));
  assert.equal(result.baseline.n,2);assert.equal(result.baseline.median,'0.08');assert.equal(result.baseline.mad,'0.01');assert.equal(result.baseline.q1,'0.07');assert.equal(result.baseline.q3,'0.09');assert.equal(returned,1);
  assert.match(sql,/"userId"=\?/);assert.match(sql,/"categoryId"=\?/);assert.match(sql,/"transactionDate">=\?/);assert.match(sql,/"transactionDate"<\?/);assert.match(sql,/array_agg/);
 });
 await t.test('authVersion checked after user lock for finalize and CRUD',async()=>{const fresh=await account();await prisma.anomalyNotificationSetting.create({data:{userId:fresh.id,enabled:true}});const row=await prisma.transaction.create({data:{userId:fresh.id,categoryId:cat.id,type:'expense',amount:'100',transactionDate:new Date('2026-09-01'),anomalyRevision:1,anomalyPending:true}});await prisma.user.update({where:{id:fresh.id},data:{authVersion:1}});await assert.rejects(withAnomalyLock(fresh,async()=>null));assert.equal(await checkTransactionAnomaly(fresh,row.id),false);await req('/transactions','POST',data(),401,fresh);assert.equal((await prisma.transaction.findUniqueOrThrow({where:{id:row.id}})).anomalyPending,true);});
});