// Real Chrome + API doubles. Does not write production data.
const fs=require('fs'),path=require('path'),os=require('os'),cp=require('child_process'),assert=require('assert/strict');
const delay=ms=>new Promise(r=>setTimeout(r,ms));const origin=process.env.SETTINGS_BROWSER_ORIGIN||'http://127.0.0.1:5173';
const mock=()=>{
 const native=window.fetch.bind(window),parts=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),today=['year','month','day'].map(k=>parts.find(p=>p.type===k).value).join('-'),current=today.slice(0,7);window.__current=current;window.__requests=[];
 window.fetch=async(url,options={})=>{
  if(!String(url).startsWith('http://localhost:4000'))return native(url,options);
  const u=new URL(url),route=u.pathname,session=new Headers(options.headers).get('Authorization')?.replace('Bearer ','')||'session-a';window.__requests.push(u.pathname+u.search);let data={};
  if(route==='/dashboard'){
   const month=u.searchParams.get('month')||current;
   if(window.__slowMonth&&month!==current||window.__slowSession&&session==='session-a')await new Promise(r=>setTimeout(r,600));
   if(window.__fail){window.__fail=false;return new Response('{}',{status:503});}
   const next=new Date(month+'-01T00:00:00Z');next.setUTCMonth(next.getUTCMonth()+1);const end=new Date(next-86400000).toISOString().slice(0,10);
   data={month,asOfDate:today,period:{startDate:month+'-01',calendarEndDate:end,effectiveEndDate:month===current?today:end,isCurrentMonth:month===current},summary:{transactionCount:2,incomeAmount:'9007199254740993.07',expenseAmount:'20.00',netCashFlow:'9007199254740973.07',budgetAmount:'10.00',budgetRemaining:'-10.00',budgetExceeded:true,hasTransactions:true},expenseCategories:[{categoryId:'food',categoryName:'หมวดยาว '.repeat(30),amount:'20.00',percentage:'100.00',transactionCount:1}],daily:[{date:month+'-01',transactionCount:2,incomeAmount:'9007199254740993.07',expenseAmount:'20.00'}],recentTransactions:{hasMore:false,items:[{id:'tx',date:month+'-01',type:'expense',amount:'20.00',categoryName:'อาหาร',description:'รายการ'}]},goals:{asOfDate:today,activeCount:1,notStartedCount:2,overdueCount:3,allocatedAmount:'0.08',primaryGoal:{id:'g',name:session+' '+month+' '+'เป้าหมายยาว '.repeat(15),archivedAt:null,calculatedStatus:'active',targetAmount:'1.00',savedAmount:'0.08',remainingAmount:'0.92',progressPercent:'8.00',progressBarPercent:'8.00'}}};
   if(window.__empty){data.summary={...data.summary,transactionCount:0,incomeAmount:'0.00',expenseAmount:'0.00',netCashFlow:'0.00',budgetAmount:null,budgetRemaining:null,budgetExceeded:false,hasTransactions:false};data.daily=[];data.expenseCategories=[];data.recentTransactions.items=[];}
  } else if(route==='/profile')data={userId:session,email:session+'@example.invalid',displayName:session,hasAvatar:false};
  else if(route==='/notifications')data={items:[],unreadCount:0};
  else if(route==='/categories')data=[{id:'food',name:'อาหาร',type:'expense'}];
  else if(route==='/transactions')data=[{id:'tx',userId:session,categoryId:'food',category:{id:'food',name:'อาหาร',type:'expense'},type:'expense',amount:'0.08',transactionDate:(u.searchParams.get('month')||'2024-02')+'-01T00:00:00Z',transactionTime:null,createdAt:today+'T00:00:00Z',updatedAt:today+'T00:00:00Z',description:'History '+session}];
  return new Response(JSON.stringify(data),{status:200,headers:{'Content-Type':'application/json'}});
 };localStorage.setItem('spendsense_token','session-a');
};
(async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'spendsense-dashboard-browser-'));const browser=cp.spawn(process.env.SETTINGS_CHROME_PATH||'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--user-data-dir='+dir,'about:blank'],{windowsHide:true,stdio:'ignore'});
 let socket;try{for(let i=0;i<100&&!fs.existsSync(path.join(dir,'DevToolsActivePort'));i++)await delay(100);const port=fs.readFileSync(path.join(dir,'DevToolsActivePort'),'utf8').split('\n')[0];const targets=await(await fetch('http://127.0.0.1:'+port+'/json/list')).json();socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j;});let id=0;const pending=new Map();socket.onmessage=e=>{const msg=JSON.parse(e.data);if(msg.id){const pair=pending.get(msg.id);pending.delete(msg.id);if(msg.error)pair.reject(Error(msg.error.message));else pair.resolve(msg.result);}};const send=(method,params={})=>new Promise((resolve,reject)=>{const key=++id;pending.set(key,{resolve,reject});socket.send(JSON.stringify({id:key,method,params}));});
 const evaluate=async(expression)=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,userGesture:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};const waitFor=async(expr)=>{for(let i=0;i<100;i++){if(await evaluate(expr))return;await delay(50);}throw Error('Timed out: '+expr);};
 await send('Page.enable');await send('Runtime.enable');await send('Page.addScriptToEvaluateOnNewDocument',{source:'('+mock.toString()+')()'});await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:origin+'/overview'});await waitFor("Boolean(document.querySelector('.dashboard-cards'))");
 assert.equal(await evaluate("getComputedStyle(document.querySelector('.dashboard-cards')).gridTemplateColumns.split(' ').length"),4);assert.equal(await evaluate("document.querySelectorAll('.user-header').length"),1);assert.equal(await evaluate("document.querySelector('.dashboard-month button:last-child').disabled"),true);assert.equal(await evaluate("document.querySelector('.dashboard-cards').textContent.includes('9,007,199,254,740,993.07')"),true);assert.equal(await evaluate("document.querySelector('.dashboard-exceeded').textContent.includes('เกินงบ')"),true);console.log('PASS desktop/current month/long exact money/negative budget');
 await evaluate("document.querySelector('summary').focus()");await send('Input.dispatchKeyEvent',{type:'keyDown',key:' ',code:'Space',windowsVirtualKeyCode:32});await send('Input.dispatchKeyEvent',{type:'keyUp',key:' ',code:'Space',windowsVirtualKeyCode:32});await waitFor("document.querySelector('details').open");assert.ok(await evaluate("document.querySelector('table').textContent.includes('ไม่มีรายการที่บันทึก')"));console.log('PASS keyboard-accessible daily table and missing-date labels');
 await evaluate("window.__slowMonth=true;document.querySelector('.dashboard-month button:first-child').click()");await waitFor("new URLSearchParams(location.search).get('month')!==window.__current");await evaluate("document.querySelector('.dashboard-month button:last-child').click()");await waitFor("Boolean(document.querySelector('.dashboard-cards'))");await delay(800);assert.equal(await evaluate("document.querySelector('.dashboard-page').textContent.includes('session-a '+window.__current)"),true);console.log('PASS old-month response ignored even when abort ignored');
 await evaluate("window.__fail=true;window.dispatchEvent(new Event('spendsense-data-changed'))");await waitFor("Boolean(document.querySelector('.dashboard-page [role=alert] button'))");await evaluate("document.querySelector('.dashboard-page [role=alert] button').focus()");await send('Input.dispatchKeyEvent',{type:'keyDown',key:' ',code:'Space',windowsVirtualKeyCode:32});await send('Input.dispatchKeyEvent',{type:'keyUp',key:' ',code:'Space',windowsVirtualKeyCode:32});await waitFor("Boolean(document.querySelector('.dashboard-cards'))");console.log('PASS error and keyboard retry');
 await evaluate("window.__slowSession=true;window.dispatchEvent(new Event('spendsense-data-changed'))");await waitFor("Boolean(document.querySelector('.dashboard-page [role=status]'))");await evaluate("localStorage.setItem('spendsense_token','session-b');window.dispatchEvent(new Event('spendsense-session'))");await waitFor("document.querySelector('.dashboard-page')?.textContent.includes('session-b '+window.__current)");await delay(800);assert.equal(await evaluate("document.querySelector('.dashboard-page').textContent.includes('session-a')"),false);console.log('PASS old-session response cannot overwrite new account');
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});assert.equal(await evaluate("getComputedStyle(document.querySelector('.dashboard-cards')).gridTemplateColumns.split(' ').length"),1);assert.equal(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'),true);console.log('PASS mobile and long text/money no page overflow');
 await evaluate("document.querySelector('a[href^=\"/transactions?month=\"]').click()");await waitFor("location.pathname==='/transactions'&&document.querySelector('.history-row')!==null").catch(async()=>{await waitFor("document.querySelector('.history-page')?.textContent.includes('History session-b')");});assert.equal(await evaluate("window.__requests.includes('/transactions?month='+window.__current)"),true);assert.equal(await evaluate("document.querySelector('.history-page').textContent.includes('กรองเดือน '+window.__current)"),true);await evaluate("[...document.querySelectorAll('.history-page a')].find(a=>a.textContent==='ดูประวัติทั้งหมด').click()");await waitFor("location.search===''&&document.querySelector('.history-page')?.textContent.includes('History session-b')");assert.equal(await evaluate("window.__requests.includes('/transactions')"),true);console.log('PASS History month link and no-month legacy request');
 await evaluate("document.querySelector('a[href=\"/overview\"]').click()");await waitFor("Boolean(document.querySelector('.dashboard-cards'))");await evaluate("window.__empty=true;window.dispatchEvent(new Event('spendsense-data-changed'))");await waitFor("Boolean(document.querySelector('.dashboard-empty'))");assert.equal(await evaluate("document.querySelectorAll('.dashboard-chart').length"),0);assert.equal(await evaluate("document.querySelector('.dashboard-cards').textContent.includes('ยังไม่ได้ตั้งงบ')"),true);console.log('PASS empty month and missing budget are explicit, no fake graph');
 await send('Browser.close').catch(()=>{});
 }finally{socket?.close();browser.kill();console.log('API-double tests only; Chrome temp profile retained outside repository.');}
})().catch(e=>{console.error(e.message);process.exitCode=1;});