// Dependency-free Chrome DevTools browser tests. API is a controlled browser-side double;
// real HTTP/database coverage lives in settings.database.test.ts. No production API writes.
const fs=require('fs'),path=require('path'),os=require('os'),cp=require('child_process'),assert=require('assert/strict');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const origin=process.env.SETTINGS_BROWSER_ORIGIN||'http://127.0.0.1:5173';
const mock=()=>{
 const native=window.fetch.bind(window);const saved={};window.__revoked=0;const revoke=URL.revokeObjectURL.bind(URL);URL.revokeObjectURL=u=>{window.__revoked++;revoke(u);};
 const data=key=>saved[key]||(saved[key]={userId:key,email:key+'@example.invalid',displayName:key==='session-b'?'บัญชีใหม่':'ผู้ใช้ทดสอบ',income:'28000.00',paydayDay:31,primaryGoalId:null,primaryGoal:null,legacyGoal:null,hasAvatar:true,goals:[{id:'goal-a',name:'เป้าหมายชื่อยาว '.repeat(12)}],budgetMonth:'2026-09',budgetAmount:null,notifications:{enabled:false,notifyNearLimit:false,notifyExceeded:false,warningPercent:80,totalBudget:true,categoryBudgets:true}});
 window.fetch=async(url,options={})=>{if(!String(url).startsWith('http://localhost:4000'))return native(url,options);const key=new Headers(options.headers).get('Authorization')?.replace('Bearer ','')||'session-a';const d=data(key),route=new URL(url).pathname;let value;
 if(window.__slow&&key==='session-a'&&(route==='/profile'||route==='/settings'))await new Promise(r=>setTimeout(r,400));
 if(route==='/settings'&&window.__failSettings&&options.method!=='PUT'){window.__failSettings=false;return new Response(JSON.stringify({error:'retry test'}),{status:503,headers:{'Content-Type':'application/json'}});}
 if(route==='/profile/avatar'){const canvas=document.createElement('canvas');canvas.width=32;canvas.height=32;const ctx=canvas.getContext('2d');ctx.fillStyle='#dbeafe';ctx.fillRect(0,0,32,32);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));return new Response(blob,{headers:{'Content-Type':'image/png'}});}
 if(route==='/profile')value={userId:d.userId,email:d.email,displayName:d.displayName,hasAvatar:d.hasAvatar};
 else if(route==='/settings'){if(options.method==='PUT'){window.__saveCount=(window.__saveCount||0)+1;await new Promise(r=>setTimeout(r,100));const input=JSON.parse(options.body);Object.assign(d,input);d.notifications={...d.notifications,notifyNearLimit:input.notifyNearLimit,notifyExceeded:input.notifyExceeded};}value=d;}
 else if(route==='/notifications')value={items:[],unreadCount:0};else if(route==='/notifications/reconcile')value={};else if(route.startsWith('/auth/'))value={logout:true};else value=[];
 return new Response(JSON.stringify(value),{headers:{'Content-Type':'application/json'}});
 };localStorage.setItem('spendsense_token','session-a');
};
(async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'spendsense-settings-browser-'));const browser=cp.spawn(process.env.SETTINGS_CHROME_PATH||'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--user-data-dir='+dir,'about:blank'],{windowsHide:true,stdio:'ignore'});
 let socket;try{for(let i=0;i<100&&!fs.existsSync(path.join(dir,'DevToolsActivePort'));i++)await delay(100);const port=fs.readFileSync(path.join(dir,'DevToolsActivePort'),'utf8').split('\n')[0];const targets=await(await fetch('http://127.0.0.1:'+port+'/json/list')).json();socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j;});let id=0;const pending=new Map();socket.onmessage=e=>{const msg=JSON.parse(e.data);if(msg.id){const pair=pending.get(msg.id);pending.delete(msg.id);if(msg.error)pair.reject(Error(msg.error.message));else pair.resolve(msg.result);}};const send=(method,params={})=>new Promise((resolve,reject)=>{const key=++id;pending.set(key,{resolve,reject});socket.send(JSON.stringify({id:key,method,params}));});
 const evaluate=async(expression)=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,userGesture:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};const waitFor=async(expr)=>{for(let i=0;i<100;i++){if(await evaluate(expr))return;await delay(50);}throw Error('Timed out: '+expr);};
 await send('Page.enable');await send('Runtime.enable');await send('Page.addScriptToEvaluateOnNewDocument',{source:'('+mock.toString()+')()'});await send('Emulation.setDeviceMetricsOverride',{width:1280,height:1000,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:origin+'/settings'});await waitFor("Boolean(document.querySelector('#settings-name'))");
 assert.equal(await evaluate("document.querySelector('#settings-email').readOnly"),true);assert.equal(await evaluate("document.querySelectorAll('input[role=switch]:disabled').length"),1);assert.equal(await evaluate("getComputedStyle(document.querySelector('.settings-grid')).gridTemplateColumns.split(' ').length"),2);console.log('PASS desktop: read-only email, two columns, disabled unsupported toggles');
 if(process.env.SETTINGS_SCREENSHOT_DIR){fs.mkdirSync(process.env.SETTINGS_SCREENSHOT_DIR,{recursive:true});const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync(path.join(process.env.SETTINGS_SCREENSHOT_DIR,'settings-desktop.png'),Buffer.from(shot.data,'base64'));}
 await evaluate("document.querySelector('input[role=switch]:not(:disabled)').focus()");await send('Input.dispatchKeyEvent',{type:'keyDown',key:' ',code:'Space',windowsVirtualKeyCode:32});await send('Input.dispatchKeyEvent',{type:'keyUp',key:' ',code:'Space',windowsVirtualKeyCode:32});assert.equal(await evaluate("document.querySelector('input[role=switch]:not(:disabled)').checked"),true);console.log('PASS keyboard Space toggles near notification');
 await evaluate("document.querySelector('#settings-name').focus()");await send('Input.insertText',{text:' แก้ไข'});await waitFor("!document.querySelector('button[type=submit]').disabled");await evaluate("document.querySelector('button[type=submit]').click();document.querySelector('button[type=submit]').click()");await waitFor("document.querySelector('.settings-success').textContent.includes('บันทึก')");await waitFor("document.querySelector('.user-header-info strong')?.textContent===document.querySelector('#settings-name')?.value");assert.equal(await evaluate('window.__saveCount'),1);console.log('PASS save refreshes shared UserHeader; duplicate submit blocked');
 await evaluate("document.querySelector('#settings-name').focus()");await send('Input.insertText',{text:' ยังไม่บันทึก'});await evaluate("window.confirm=()=>false;document.querySelector('a[href=\"/overview\"]').click()");assert.equal(await evaluate('location.pathname'),'/settings');await evaluate("document.querySelector('.sidebar-logout').click()");assert.equal(await evaluate("localStorage.getItem('spendsense_token')"),'session-a');console.log('PASS cancelled logout retains current session');await evaluate("[...document.querySelectorAll('.settings-actions button')].find(b=>b.textContent==='ยกเลิก').click()");await waitFor("Boolean(document.querySelector('#settings-name')) && document.querySelector('button[type=submit]').disabled");console.log('PASS dirty navigation blocked; Cancel reloads server values');
 await evaluate("window.__failSettings=true;document.querySelector('.settings-actions button[type=button]').click()");await waitFor("Boolean(document.querySelector('.settings-error button'))");await evaluate("document.querySelector('.settings-error button').click()");await waitFor("Boolean(document.querySelector('#settings-name')) && !document.querySelector('.settings-error button')");console.log('PASS loading/error/retry restores server values');
 await evaluate("const trigger=[...document.querySelectorAll('button')].find(b=>b.textContent==='เปลี่ยนรหัสผ่าน');trigger.focus();trigger.click()");await waitFor("document.querySelector('dialog.settings-dialog')?.open");assert.equal(await evaluate('document.activeElement.id'),'current-password');for(let i=0;i<7;i++){await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});assert.equal(await evaluate("Boolean(document.activeElement.closest('dialog.settings-dialog'))"),true);}console.log('PASS dialog keyboard focus remains inside modal');await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await waitFor("!document.querySelector('dialog.settings-dialog')");await waitFor('document.activeElement===trigger');console.log('PASS native dialog focus, Escape, focus restoration');
 await evaluate("document.querySelector('#settings-name').focus()");await send('Input.insertText',{text:'ยาว'.repeat(30)});await evaluate("document.querySelector('#settings-income').focus()");await send('Input.insertText',{text:'9999999999.99'});await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});assert.equal(await evaluate("getComputedStyle(document.querySelector('.settings-grid')).gridTemplateColumns.split(' ').length"),1);assert.equal(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'),true);console.log('PASS mobile single column and long text/money no horizontal overflow');if(process.env.SETTINGS_SCREENSHOT_DIR){const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync(path.join(process.env.SETTINGS_SCREENSHOT_DIR,'settings-mobile.png'),Buffer.from(shot.data,'base64'));}
 await evaluate("window.__slow=true;window.confirm=()=>true;[...document.querySelectorAll('.settings-actions button')].find(b=>b.textContent==='ยกเลิก').click();localStorage.setItem('spendsense_token','session-b');window.dispatchEvent(new Event('spendsense-session'))");await waitFor("document.querySelector('#settings-name')?.value==='บัญชีใหม่'");await delay(600);assert.equal(await evaluate("document.querySelector('#settings-name').value"),'บัญชีใหม่');assert.equal(await evaluate("document.querySelector('.user-header-info strong').textContent"),'บัญชีใหม่');assert.ok(await evaluate('window.__revoked>0'));console.log('PASS stale session responses ignored and avatar Blob URLs revoked');
 await evaluate("localStorage.removeItem('spendsense_token');window.dispatchEvent(new Event('spendsense-session'))");await delay(100);assert.equal(await evaluate("document.querySelector('.user-header-info strong')?.textContent==='บัญชีใหม่'"),false);console.log('PASS logout clears profile view');
 console.log('Browser API-double assertions PASS (not real backend acceptance)');await send('Browser.close').catch(()=>{});
 }finally{socket?.close();browser.kill();console.log('Temporary browser profile retained outside repository; no fixture images written.');}
})().catch(e=>{console.error(e.message);process.exitCode=1;});